language: node_js
node_js: stable
services:
  - mongodb
env:
  - MONGODB_URI=mongodb://localhost/nazrin
after_success:
  - npm run coverage
notifications:
  email:
    on_success: never
    on_failure: change
